codecov:
  notify:
    wait_for_ci: true
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
comment:
  layout: "Header, Reach, Tree"
  behavior: default
  require_changes: false
