include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/*.config.dart"

  errors:
    missing_required_param: error
    missing_return: error
    prefer_const_constructors: error
    always_declare_return_types: warning

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - prefer_const_constructors
    - prefer_single_quotes
    - prefer_interpolation_to_compose_strings

    - avoid_unnecessary_containers
    - unnecessary_this
    - unnecessary_lambdas

    - prefer_relative_imports
    - avoid_dynamic_calls
    - avoid_types_as_parameter_names
    - avoid_null_checks_in_equality_operators

    - prefer_const_literals_to_create_immutables
    - use_key_in_widget_constructors
