name: cacherine
description: A Dart library that provides flexible in-memory cache implementations including FIFO, LRU, MRU, and LFU, with both single-threaded and async-enabled options for concurrent environments.
version: 1.0.2
repository: https://github.com/yordgenome03/cacherine

dependencies:
  synchronized: ^3.3.0+3

environment:
  sdk: ">=2.19.0 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

license: MIT
