name: cacherine
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/yordgenome03/cacherine

dependencies:
  synchronized: ^3.3.0+3

environment:
  sdk: ">=2.19.0 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

license: MIT
