name: cacherine
description: A Dart library offering flexible in-memory cache implementations (FIFO, LRU, MRU, LFU) with both single-threaded and async options for concurrent environments.
version: 1.1.1
repository: https://github.com/yordgenome03/cacherine

dependencies:
  synchronized: ^3.3.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

license: MIT
