name: cacherine
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/yordgenome03/cacherine

environment:
  sdk: ^3.5.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

license: MIT
