name: "✨ Feature Request"
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        Thank you for suggesting an improvement or a new feature!

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see.
      placeholder: I want cacherine to support...

  - type: textarea
    id: why-needed
    attributes:
      label: Why is this needed?
      description: Explain why this feature would be useful.
      placeholder: This would help developers because...

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Provide ideas on how this feature could be implemented.
      placeholder: A possible implementation could be...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/YOUR_REPO/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
